version: '3.10'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: booking
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgAdmin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - booking-network

  booking:
    build:
      context: ./booking
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      DB_NAME: 'booking'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres123'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      EMAIL_USE_TLS: 'True'
      EMAIL_HOST: 'smtp.gmail.com'
      EMAIL_HOST_USER: 'varanchukv@gmail.com'
      EMAIL_HOST_PASSWORD: 'mwoa ppyv lrfl bksf'
      EMAIL_PORT: '587'
    volumes:
      - ./booking:/app
      - static_volume:/app/static
    networks:
      - booking-network

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    networks:
      - booking-network
    depends_on:
      - booking

volumes:
  postgres_data:
  pgadmin-data:
  static_volume:

networks:
  booking-network:
    driver: bridge
