# Generated by Django 5.0.3 on 2024-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
