# Generated by Django 5.0.3 on 2024-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_roommodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomodel',
            name='photo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
