# Generated by Django 5.0.3 on 2024-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_photomodel_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelmodel',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
