# Generated by Django 5.0.3 on 2024-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelmodel_city_hotelmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
