# Generated by Django 5.0.3 on 2024-05-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_roommodel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelStatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_bookings', models.IntegerField(default=0)),
                ('total_number_of_reviews', models.IntegerField(default=0)),
                ('user_rating', models.FloatField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelmodel')),
            ],
        ),
    ]
