# Generated by Django 5.0.3 on 2024-03-30 17:42

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_roommodel_number'),
        ('reservations', '0002_BtreeGistExtension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='booking_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='bookingmodel',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('cancelled', False)), expressions=[('booking_range', '&&'), ('room_id', '=')], name='exclude_overlapping_reservations'),
        ),
    ]
