# Generated by Django 5.0.3 on 2024-03-31 11:56

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_roommodel_number'),
        ('reservations', '0002_BtreeGistExtension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='bookingmodel',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('cancelled', False)), expressions=[(reservations.models.DateRange('check_in_date', 'check_out_date', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('room_id', '=')], name='exclude_overlapping_reservations'),
        ),
    ]
