# Generated by Django 5.0.3 on 2024-03-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_bookingmodel_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='slug',
        ),
    ]
